version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=thePriceIsRight
    ports:
      - "5432:5432"
    volumes:
      - priceIsRightpostgresDatabase:/var/lib/postgresql/data
    
volumes:
  priceIsRightpostgresDatabase: